function cleanup_Release_folder
% Delete files and folders that are safe to delete under the Release folder.

% Copyright 2025 The MathWorks, Inc.

release_top_folder = "C:\local\modutil\modeling-utility\Release";
assert(isfolder(release_top_folder))

% Delete the folder generated by the build tool.
folder_to_delete = fullfile(release_top_folder, ".buildtool");
if isfolder(folder_to_delete)
  rmdir(folder_to_delete, "s")
end  % if

% Delete the folder generated to store unit test results.
folder_to_delete = fullfile(release_top_folder, "test-result");
if isfolder(folder_to_delete)
  rmdir(folder_to_delete, "s")
end  % if

% -----------------------------------------------------------------------------
% Delete files under the "Release > ModelingUtilityForSimscape" folder.
target_folder = fullfile(release_top_folder, "ModelingUtilityForSimscape");
if not(isfolder(target_folder))
  disp("There is no ModelingUtilityForSimscape folder.")

  return

end  % if
disp("Removing the ModelingUtilityForSimscape folder")

targets_to_delete = matlab.buildtool.io.FileCollection.fromPaths(fullfile(target_folder, "**")).paths';

FilesToDelete = targets_to_delete(isfile(targets_to_delete));

FoldersToDelete = targets_to_delete(isfolder(targets_to_delete));

if not(isempty(FilesToDelete))
  delete(FilesToDelete{:})
end  % if

if not(isempty(FoldersToDelete))
  for ii = 1 : numel(FoldersToDelete)
    if isfolder(FoldersToDelete(ii))
      rmdir(FoldersToDelete(ii), "s")
    end  % for
  end  % if
end  % if
end  % function
