function cleanup_Release_folder(NameValuePair)
% Delete files and folders that are safe to delete under the Release folder.
%
% By default, this function reports the target files and folders to delete but does not delete them.
% Use the DryRun=false option to actually delete.
%
% For this function to work, the folder tree must be version-managed with git.

% Copyright 2025-2026 The MathWorks, Inc.

arguments (Input)
  NameValuePair.DryRun (1,1) logical = true
end  % arguments

try
  repo = gitrepo;
catch exception

  rethrow(exception)

end  % try, catch
repo_top_folder = repo.WorkingFolder;

release_top_folder = fullfile(repo_top_folder, "Release");
assert(isfolder(release_top_folder))

% Delete the folder generated by the build tool.
folder_to_delete = fullfile(release_top_folder, ".buildtool");
if isfolder(folder_to_delete)
  cmd = "rmdir(""" + folder_to_delete + """, ""s"")";
  if NameValuePair.DryRun
    disp("Dry run: " + cmd)
  else
    disp(folder_to_delete)
    eval(cmd)
  end  % if
end  % if

% Delete the folder generated to store unit test results.
folder_to_delete = fullfile(release_top_folder, "test-result");
if isfolder(folder_to_delete)
  cmd = "rmdir(""" + folder_to_delete + """, ""s"")";
  if NameValuePair.DryRun
    disp("Dry run: " + cmd)
  else
    disp(folder_to_delete)
    eval(cmd)
  end  % if
end  % if

% Delete the folder generated to store unit test results.
folder_to_delete = fullfile(release_top_folder, "test-result-24b");
if isfolder(folder_to_delete)
  cmd = "rmdir(""" + folder_to_delete + """, ""s"")";
  if NameValuePair.DryRun
    disp("Dry run: " + cmd)
  else
    disp(folder_to_delete)
    eval(cmd)
  end  % if
end  % if

% -----------------------------------------------------------------------------
% Delete files under the "Release > ModelingUtilityForSimscape" folder.
target_folder = fullfile(release_top_folder, "ModelingUtilityForSimscape");
if not(isfolder(target_folder))
  disp("There is no ModelingUtilityForSimscape folder.")

  return

end  % if
disp("Removing the ModelingUtilityForSimscape folder...")

targets_to_delete = matlab.buildtool.io.FileCollection.fromPaths(fullfile(target_folder, "**")).paths';

FilesToDelete = targets_to_delete(isfile(targets_to_delete));

FoldersToDelete = targets_to_delete(isfolder(targets_to_delete));

if not(isempty(FilesToDelete))
  for ii = 1 : numel(FilesToDelete)
    cmd = "delete(""" + FilesToDelete(ii) + """)";
    if isfile(FilesToDelete(ii))
      if NameValuePair.DryRun
        disp("Dry run: " + cmd)
      else
        disp(FilesToDelete(ii))
        eval(cmd)
      end  % if
    end  % for
  end  % if
end  % if

if not(isempty(FoldersToDelete))
  for ii = 1 : numel(FoldersToDelete)
    cmd = "rmdir(""" + FoldersToDelete(ii) + """, ""s"")";
    if isfolder(FoldersToDelete(ii))
      if NameValuePair.DryRun
        disp("Dry run: " + cmd)
      else
        disp(FoldersToDelete(ii))
        eval(cmd)
      end  % if
    end  % for
  end  % if
end  % if
end  % function
