classdef unittest_summarizeCodeCoverage < matlab.unittest.TestCase
  % Class-based unit test

  % Author Class-Based Unit Tests in MATLAB
  % https://www.mathworks.com/help/matlab/matlab_prog/author-class-based-unit-tests-in-matlab.html
  %
  % matlab.unittest.TestCase Class
  % https://www.mathworks.com/help/matlab/ref/matlab.unittest.testcase-class.html
  %
  % Test Browser
  % https://www.mathworks.com/help/matlab/ref/testbrowser-app.html

  % Copyright 2025 The MathWorks, Inc.

  methods (TestMethodSetup)
    % Functions in this section always run before each test defined in the Test section runs.

    function test_method_setup_1(testcase)
      function closeAll
        close all
        bdclose all
      end  % nested function
      closeAll
      % addTeardown adds a function which always runs after each test.
      % Even if the execution of a test ends with an error, the teardown function runs.
      addTeardown(testcase, @closeAll)
    end  % function

  end  % methods

  methods (Test)
    % Functions in this "Test" section are the tests.
    % Before each function in this section runs, functions defined in the TestMethodSetup section run.

    %% Minimum quality check
    % Check that models, scripts, functions, and classes run right out of the box.

    % Error cases

    function Test_error_1(testcase)
      verifyError(testcase, @() test_target, "MATLAB:minrhs")
      function test_target
        TestUtil1.summarizeCodeCoverage
      end  % nested function
    end  % function

    % Passing tests

    function PassingTest_1(~)
      demo_summarizeCodeCoverage_1
    end  % function

    function PassingTest_2(~)
      demo_summarizeCodeCoverage_2
    end  % function

    %% Regular tests

    function Test_1(testcase)
      % Test that the function returns the expected table.
      % Use a proper test result XML file generated by the Build Tool.
      target_file = SearchUtil1.searchFiles("sample-code-coverage-1.xml");
      assert(not(isempty(target_file)), "Target file was not found. Make sure the TopFolder tree has one or more target files.")

      target_file = target_file(1, :);
      disp("Using this coverage file: " + target_file)

      result = TestUtil1.summarizeCodeCoverage(target_file);  % !test-target

      total_coverage = result.TotalCoverageTable;
      verifyTrue(testcase, height(total_coverage) == 1)
      verifyTrue(testcase, ismember("StatementCoveragePercent", string(total_coverage.Properties.VariableNames)))
      verifyTrue(testcase, ismember("LinesCovered", string(total_coverage.Properties.VariableNames)))
      verifyTrue(testcase, ismember("LinesValid", string(total_coverage.Properties.VariableNames)))
      verifyTrue(testcase, ismember("TimeStamp", string(total_coverage.Properties.VariableNames)))
      verifyTrue(testcase, isprop(total_coverage.Properties.CustomProperties, "TopFolder"))

      component_coverage = result.ComponentCoverageTable;
      verifyTrue(testcase, height(component_coverage) > 0)
      verifyTrue(testcase, ismember("ComponentName", string(component_coverage.Properties.VariableNames)))
      verifyTrue(testcase, ismember("ComponentCoveragePercent", string(component_coverage.Properties.VariableNames)))

      file_coverage = result.FileCoverageTable;
      verifyTrue(testcase, height(file_coverage) > 0)
      verifyTrue(testcase, ismember("StatementCoveragePercent", string(file_coverage.Properties.VariableNames)))
      verifyTrue(testcase, ismember("TestClassName", string(file_coverage.Properties.VariableNames)))
      verifyTrue(testcase, ismember("FilePath", string(file_coverage.Properties.VariableNames)))

    end  % function

  end  % methods
end  % classdef
