%[text] # checkRefSubInCallbackButton demo
%[text] `checkRefSubInCallbackButton` works with MATLAB R2025a or newer.
model_name = "samplemodel_checkRefSubInCallbackButton";
result = ModelUtil1.checkRefSubInCallbackButton(model_name, DisplayInfo=true); %[output:769dd1df]
disp(result) %[output:61a579a5]
%[text] *Copyright 2025 The MathWorks, Inc.*

%[appendix]{"version":"1.0"}
%---
%[metadata:view]
%   data: {"layout":"inline"}
%---
%[output:769dd1df]
%   data: {"dataType":"text","outputData":{"text":"Checking Callback Button [1]: samplemodel_checkRefSubInCallbackButton\/Select 1\nChecking code [1]: set_param(gcs+\"\/Component 1\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub1\")\nChecking Callback Button [2]: samplemodel_checkRefSubInCallbackButton\/Select 2\nChecking code [1]: set_param(gcs+\"\/Component 1\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub2\")\nChecking Callback Button [3]: samplemodel_checkRefSubInCallbackButton\/Select 3\nChecking code [1]: set_param(gcs+\"\/Component 1\", ReferencedSubsystem=\"dummy\")\nChecking Callback Button [4]: samplemodel_checkRefSubInCallbackButton\/Select 4\nChecking code [1]: set_param(gcs+\"\/Component 2\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub1\")\nChecking code [2]: set_param(gcs+\"\/Component 3\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub1\")\nChecking code [3]: set_param(gcs+\"\/Component 4\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub1\")\nChecking Callback Button [5]: samplemodel_checkRefSubInCallbackButton\/Select 5\nChecking code [1]: set_param(gcs+\"\/Component 2\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub2\")\nChecking code [2]: set_param(gcs+\"\/Component 3\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub2\")\nChecking code [3]: set_param(gcs+\"\/Component 4\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub2\")\nChecking Callback Button [6]: samplemodel_checkRefSubInCallbackButton\/Select 6\nChecking code [1]: set_param(gcs+\"\/Component 2\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub1\")\nChecking code [2]: set_param(gcs+\"\/Component 3\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub2\")\nChecking code [3]: set_param(gcs+\"\/Component 4\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub3\")\nChecking Callback Button [7]: samplemodel_checkRefSubInCallbackButton\/Subsystem\/Select 7\nChecking code [1]: set_param(gcs+\"\/Component 5\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub1\")\nChecking Callback Button [8]: samplemodel_checkRefSubInCallbackButton\/Subsystem\/Select 8\nChecking code [1]: set_param(gcs+\"\/Component 5\", ReferencedSubsystem=\"samplemodel_checkRefSubInCallbackButton_refsub2\")\n","truncated":false}}
%---
%[output:61a579a5]
%   data: {"dataType":"text","outputData":{"text":"                             <strong>BlockPath<\/strong>                                                  <strong>FileName<\/strong>                         <strong>Found<\/strong>    <strong>IsRefSub<\/strong>\n    <strong>____________________________________________________________<\/strong>    <strong>_________________________________________________<\/strong>    <strong>_____<\/strong>    <strong>________<\/strong>\n\n    \"samplemodel_checkRefSubInCallbackButton\/Select 1\"              \"samplemodel_checkRefSubInCallbackButton_refsub1\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 2\"              \"samplemodel_checkRefSubInCallbackButton_refsub2\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 3\"              \"dummy\"                                              false     false  \n    \"samplemodel_checkRefSubInCallbackButton\/Select 4\"              \"samplemodel_checkRefSubInCallbackButton_refsub1\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 4\"              \"samplemodel_checkRefSubInCallbackButton_refsub1\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 4\"              \"samplemodel_checkRefSubInCallbackButton_refsub1\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 5\"              \"samplemodel_checkRefSubInCallbackButton_refsub2\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 5\"              \"samplemodel_checkRefSubInCallbackButton_refsub2\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 5\"              \"samplemodel_checkRefSubInCallbackButton_refsub2\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 6\"              \"samplemodel_checkRefSubInCallbackButton_refsub1\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 6\"              \"samplemodel_checkRefSubInCallbackButton_refsub2\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Select 6\"              \"samplemodel_checkRefSubInCallbackButton_refsub3\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Subsystem\/Select 7\"    \"samplemodel_checkRefSubInCallbackButton_refsub1\"    true      true   \n    \"samplemodel_checkRefSubInCallbackButton\/Subsystem\/Select 8\"    \"samplemodel_checkRefSubInCallbackButton_refsub2\"    true      true   \n\n","truncated":false}}
%---
