function CoverageSummary = summarizeCodeCoverage(CodeCoverageFile)
% Summarize code coverage information from a Cobertura XML coverage file.
%
% This function takes an XML file in Cobertura format which was generated by
% the Build Tool.
% The coverage handled in this function is statement coverage (C0 coverage.)
%
%
% See also:
%
% For more fine-grained coverage analysis and reporting, use a test runner with code coverage plugin.
%
% - matlab.unittest.plugins.CodeCoveragePlugin Class
%   https://www.mathworks.com/help/matlab/ref/matlab.unittest.plugins.codecoverageplugin-class.html
%
% - matlab.coverage.Result Class
%   https://www.mathworks.com/help/matlab/ref/matlab.coverage.result-class.html
%
% - generateCoberturaReport
%   https://www.mathworks.com/help/matlab/ref/matlab.coverage.result.generatecoberturareport.html

% Copyright 2025 The MathWorks, Inc.

arguments (Input)
  CodeCoverageFile (1,1) string {mustBeFile}
end  % arguments

arguments (Output)
  CoverageSummary struct
end  % arguments

cov_struct = readstruct(CodeCoverageFile);

% -----------------------------------------------------------------------------
% Top-level coverage

% In the code coverage file, attribute values are double-quoted text. However,
% the "*Attribute" values generated by readstruct for line-rate, line-covered,
% lines-valid, and timestemp are numeric values.
line_rate = cov_struct.line_rateAttribute;
StatementCoveragePercent = line_rate * 100;
LinesCovered = cov_struct.lines_coveredAttribute;
LinesValid = cov_struct.lines_validAttribute;
time_stamp_posix = cov_struct.timestampAttribute;
TimeStamp = "UTC " + string(datetime(time_stamp_posix, ConvertFrom="posixtime", TimeZone="UTC", Format="yyyy-MM-dd HH:mm:ss"));

TotalCoverage = table(StatementCoveragePercent, LinesCovered, LinesValid, TimeStamp);

top_folder = cov_struct.sources.source;

TotalCoverage = addprop(TotalCoverage, "TopFolder", "table");
TotalCoverage.Properties.CustomProperties.TopFolder = top_folder;

CoverageSummary = struct;
CoverageSummary.TotalCoverage = TotalCoverage;

% -----------------------------------------------------------------------------
% Component-level coverage
cov_packages = cov_struct.packages.package;
num_packages = numel(cov_packages);
% package_names = strings(num_packages, 1);
empty_package_name_index = ([cov_packages.nameAttribute] == "");
num_targets = nnz(~empty_package_name_index);
ComponentName = strings(num_targets, 1);
ComponentCoveragePercent = nan(num_targets, 1);
cnt1 = 0;
for pp = 1 : num_packages
  current_package = cov_packages(pp);
  if current_package.nameAttribute == ""

    continue

  end  % for
  cnt1 = cnt1 + 1;
  ComponentName(cnt1) = current_package.nameAttribute;
  ComponentCoveragePercent(cnt1) = current_package.line_rateAttribute * 100;
end  % for

ComponentCoveragePercent = table(ComponentName, ComponentCoveragePercent);
ComponentCoveragePercent = sortrows(ComponentCoveragePercent, 'ComponentName');

CoverageSummary.ComponentCoverage = ComponentCoveragePercent;

% -----------------------------------------------------------------------------
% File-level coverage
% Statement coverage (C0 coverage) information in individual files.

assert(nnz(empty_package_name_index) == 1)

target_classes = cov_packages(empty_package_name_index).classes.class;

num_targets = numel(target_classes);

TestClassName = strings(num_targets, 1);
FilePath = strings(num_targets, 1);
StatementCoveragePercent = nan(num_targets, 1);

for cc = 1 : num_targets
  current_class = target_classes(cc);
  TestClassName(cc) = current_class.nameAttribute;
  FilePath(cc) = current_class.filenameAttribute;
  line_rate = current_class.line_rateAttribute;
  StatementCoveragePercent(cc) = line_rate * 100;
end  % for

FileCoverage = table(StatementCoveragePercent, TestClassName, FilePath);
FileCoverage = sortrows(FileCoverage, {'StatementCoveragePercent', 'FilePath'});

CoverageSummary.FileCoverage = FileCoverage;

end  % function
