classdef unittest_getTestResultTable < matlab.unittest.TestCase
  % Class-based unit test

  % Author Class-Based Unit Tests in MATLAB
  % https://www.mathworks.com/help/matlab/matlab_prog/author-class-based-unit-tests-in-matlab.html
  %
  % matlab.unittest.TestCase Class
  % https://www.mathworks.com/help/matlab/ref/matlab.unittest.testcase-class.html
  %
  % Test Browser
  % https://www.mathworks.com/help/matlab/ref/testbrowser-app.html

  % Copyright 2026 The MathWorks, Inc.

  methods (TestMethodSetup)
    % Functions in this section always run before each test defined in the Test section runs.

    function test_method_setup_1(testcase)
      function closeAll
        close all
        bdclose all
      end  % nested function
      closeAll
      % addTeardown adds a function which always runs after each test.
      % Even if the execution of a test ends with an error, the teardown function runs.
      addTeardown(testcase, @closeAll)
    end  % function

  end  % methods

  methods (Test)
    % Functions in this "Test" section are the tests.
    % Before each function in this section runs, functions defined in the TestMethodSetup section run.

    %% Minimum quality check
    % Check that models, scripts, functions, and classes run right out of the box.

    % Error cases

    function Test_error_1(testcase)
      verifyError(testcase, @() test_target, "MATLAB:minrhs")
      function test_target
        TestUtil1.getTestResultTable
      end  % nested function
    end  % function

    function Test_error_2(testcase)
      verifyError(testcase, @() test_target, "MATLAB:validators:mustBeNonzeroLengthText")
      function test_target
        TestUtil1.getTestResultTable("")
      end  % nested function
    end  % function

    function Test_error_3(testcase)
      verifyError(testcase, @() test_target, "MATLAB:validators:mustBeFile")
      function test_target
        TestUtil1.getTestResultTable("dummy_dummy_dummy")
      end  % nested function
    end  % function

    % Passing tests

    function PassingTest_1(~)
      demo_getTestResultTable_1
    end  % function

    %% Regular tests

    function Test_1(testcase)
      % Test that the function returns the expected table.
      % Use a proper test result XML file generated by the Build Tool.
      target_file = SearchUtil1.searchFiles("sample-test-result-22tests-2errors.xml");
      assert(not(isempty(target_file)), "Target file was not found. Make sure the TopFolder tree has one or more target files.")
      target_file = target_file(1, :);
      result = TestUtil1.getTestResultTable(target_file);
      verifyTrue(testcase, height(result) > 0)

      % Table's custom properties
      verifyTrue(testcase, isprop(result.Properties.CustomProperties, "NumberOfTests"))
      verifyTrue(testcase, isprop(result.Properties.CustomProperties, "NumberOfErrors"))
      verifyTrue(testcase, isprop(result.Properties.CustomProperties, "NumberOfFailures"))
      verifyTrue(testcase, isprop(result.Properties.CustomProperties, "NumberOfSkips"))
      verifyTrue(testcase, isprop(result.Properties.CustomProperties, "TotalTestTimeInSeconds"))
      verifyTrue(testcase, isprop(result.Properties.CustomProperties, "MeanTestTimeInSeconds"))
      verifyTrue(testcase, isprop(result.Properties.CustomProperties, "MedianTestTimeInSeconds"))

      % Table's variable names = column names
      verifyTrue(testcase, ismember("TestPassed", string(result.Properties.VariableNames)))
      verifyTrue(testcase, ismember("TestClass", string(result.Properties.VariableNames)))
      verifyTrue(testcase, ismember("TestFunction", string(result.Properties.VariableNames)))
      verifyTrue(testcase, ismember("TestTimeInSeconds", string(result.Properties.VariableNames)))
    end  % function

  end  % methods
end  % classdef
