%% Find files containing Visible="on" and movegui
% This script was meant to be temporary for a quick fix work, but
% this is kept as an example of running two text searches, merging the search results,
% and showing the merged table in an app which can open the file with double-click.

% Copyright 2025 The MathWorks, Inc.

session1 = SearchUtil1.searchText( ...
  "Visible = ""on""", ...
  IgnoreCase = false, ...
  MatchWholeWord = false, ...
  TargetFolder = "C:\local\modutil\modeling-utility\Devel", ...
  IncludeSubfolders = true, ...
  FileTypes = "*.m", ...
  ExcludeLiveScript = false, ...
  ExcludeMATLABCodeFile = false);

top_folder = session1.Searcher.States.TargetFolder;

session2 = SearchUtil1.searchText( ...
  "movegui", ...
  IgnoreCase = false, ...
  MatchWholeWord = false, ...
  TargetFolder = "C:\local\modutil\modeling-utility\Devel", ...
  IncludeSubfolders = true, ...
  FileTypes = "*.m", ...
  ExcludeLiveScript = false, ...
  ExcludeMATLABCodeFile = false);

% TextSearchResultViewerApp(session1.Searcher, SearchResult=session1.Result)
% TextSearchResultViewerApp(session2.Searcher, SearchResult=session2.Result)

%%

t1visible = session1.Result;
t2movegui = session2.Result;

% True if the code has movegui.
HasMovegui = ismember(t1visible.FilePath, t2movegui.FilePath);

if all(HasMovegui)
  disp("All files have movegui.")
else
  disp("Number of files missing movegui: " + numel(HasMovegui(~HasMovegui)))
end  % if

FilePath = t1visible.FilePath;

LineNumber = t1visible.LineNumber;

target_table = table(HasMovegui, FilePath, LineNumber);

FileListApp(target_table, TopFolder=top_folder, ColumnWidth={'fit', '1x', 'fit'})
